import type { FeedGroup } from '../app/types/feed'
// 友链检测 CLI 需要使用显式导入和相对路径
import { myFeed } from '../blog.config'
// eslint-disable-next-line unused-imports/no-unused-imports
import { getFavicon, getGithubAvatar, getGithubIcon, getOciqGroupAvatar, getOicqAvatar, OicqAvatarSize } from './utils/img'

export default [
	// #region Clarity
	{
		name: '清晰体验',
		desc: '使用 Clarity 博客主题构建的网站。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			myFeed,
			{
				author: 'GuuGuai',
				sitenick: '杂记本',
				title: '古怪杂记本',
				desc: '一个什么都可能会写的博客',
				link: 'https://blog.guuguai.site/',
				feed: 'https://blog.guuguai.site/atom.xml',
				icon: 'https://cravatar.cn/avatar/646331BFF8F19A0E05679C3CC0FC54D6',
				avatar: 'https://cdn.libravatar.org/avatar/646331bff8f19a0e05679c3cc0fc54d6?s=160',
				archs: ['Nuxt', 'Netlify'],
				date: '2026-07-01',
				comment: '爱好番剧/折腾。',
			},
			{
				author: '小李同学',
				sitenick: 'Coding',
				title: '小李同学 Coding',
				desc: '一支努力变强的小彩笔',
				link: 'https://blog.junjieli.top/',
				feed: 'https://blog.junjieli.top/atom.xml',
				icon: 'https://blog.junjieli.top/api/icon.webp',
				avatar: 'https://www.junjieli.top/logo_64x64.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2026-07-01',
				comment: '瓜大网安学长。',
			},
			{
				author: 'Xlenco',
				sitenick: '希乐博客',
				desc: '互联网中的静谧之地',
				link: 'https://blog.xlenco.top/',
				feed: 'https://blog.xlenco.top/atom.xml',
				icon: 'https://weavatar.com/avatar/67254b346498965226e5c91ebff66a69570b97f224d2d061e504b4eade1f00fa',
				avatar: getOicqAvatar('1043865083'),
				archs: ['Nuxt', 'EdgeOne'],
				date: '2026-07-01',
				comment: '经验分享。',
			},
			{
				author: '梦爱吃鱼',
				desc: '不负心灵，不负今生。',
				link: 'https://blog.bsgun.cn/',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: 'https://www.bsgun.cn/favicon.ico',
				avatar: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2026-07-01',
				comment: '博客折腾',
			},
			{
				author: '鹊楠',
				sitenick: '小窝',
				title: '鹊楠の小窝',
				desc: '世界那么大，我想去看看',
				link: 'https://blog.quenan.cn/',
				feed: 'https://blog.quenan.cn/atom.xml',
				icon: 'https://pic1.imgdb.cn/item/6900c4b13203f7be00ac9ded.png',
				avatar: 'https://pic1.imgdb.cn/item/69d51522cfae5fcb267af121.webp',
				archs: ['Nuxt', 'Vercel'],
				date: '2026-07-01',
				comment: '技术分享。',
			},
			{
				author: '东方月初',
				sitenick: 'BiuXin',
				title: 'BiuXin-s Blog',
				desc: '人生的每一天，都在学习当中',
				link: 'https://blog.biuxin.de/',
				feed: 'https://blog.biuxin.de/atom.xml',
				icon: 'https://x.xinb.de/i/2024/09/19/040857.webp',
				avatar: getGithubAvatar('damizai'),
				archs: ['Nuxt', 'Cloudflare'],
				date: '2026-07-01',
				comment: '软件工具资源，博客部署美化。',
			},
			{
				author: 'Shenley',
				sitenick: '存档点',
				title: 'Shenley的存档点',
				desc: '随手存个档～',
				link: 'https://blog.shenley.cn/',
				feed: 'https://blog.shenley.cn/atom.xml',
				icon: 'https://blog.shenley.cn/avatar.jpg',
				avatar: 'https://blog.shenley.cn/avatar.jpg',
				archs: ['Nuxt', 'Vercel'],
				date: '2026-07-01',
				comment: '前端开发、生活分享。',
			},
			{
				author: '液泡',
				sitenick: '部落格',
				title: '液泡部落格',
				desc: '一介书生，三尺微命',
				link: 'https://blog.vacu.top/',
				feed: 'https://blog.vacu.top/atom.xml',
				icon: 'https://blog.vacu.top/favicon.ico',
				avatar: 'https://blog.vacu.top/assets/img/avatar.png',
				archs: ['Nuxt', 'Cloudflare'],
				date: '2026-07-01',
				comment: '对世界的学习与思考。',
			},
			{
				author: '月空人',
				desc: '偶尔写些博客，发发牢骚',
				link: 'https://www.weilog.me/',
				feed: 'https://www.weilog.me/atom.xml',
				icon: 'https://www.weilog.me/favicon.ico',
				avatar: 'https://bitmc.uno/picgo/126662463_p2.jpg',
				archs: ['Nuxt', 'Vercel'],
				date: '2026-07-01',
				comment: '前端大手子，运营prop.show播客，分享前端技术的心得。',
			},
			{
				author: '落憾',
				sitenick: 'EnLtLH',
				title: '落憾',
				desc: '建此博客，以示吾思。话天篆地，自由吾心。',
				link: 'https://blog.luoh.org/',
				feed: 'https://blog.luoh.org/atom.xml',
				icon: 'https://cdn2.elh.dpdns.org/picture/2025/5223b2101b56608abd83b63642984b1f.avif',
				avatar: 'https://cdn2.elh.dpdns.org/picture/2025/57bd486ead4f5b34a28aea7f160a70ae.avif',
				archs: ['Nuxt', 'Vercel'],
				date: '2026-07-01',
				comment: '以诗词、杂记等形式记录感悟与创作。',
			},
			{
				author: 'AirTouch',
				desc: '分享技术、生活、思考。',
				link: 'https://www.xsl.im/',
				feed: 'https://www.xsl.im/atom.xml',
				icon: 'https://www.xsl.im/favicon.webp',
				avatar: 'https://www.xsl.im/avatar.webp',
				archs: ['Nuxt', '服务器'],
				date: '2026-07-01',
				comment: '网站反代配置、服务器评测、域名更换、存储加速、工具推荐、编程题解等折腾与技术分享。',
			},
			{
				author: '筱序二十',
				sitenick: '青序栈',
				desc: '青序成栈·向简而生',
				link: 'https://www.qixz.cn/',
				feed: 'https://www.qixz.cn/feed/',
				icon: 'https://www.qixz.cn/favicon.svg',
				avatar: 'https://www.qixz.cn/avatar.avif',
				archs: ['Nuxt', '国内 CDN'],
				date: '2026-07-01',
				comment: '网站攻击处理曝光，博客配置魔改等技术教程与资源分享。',
			},
			{
				author: 'fishcpy',
				sitenick: '小破站',
				title: 'fishcpy的小破站',
				desc: '非淡泊无以明志，非宁静无以致远',
				link: 'https://blog.fis.ink/',
				feed: 'https://blog.fis.ink/atom.xml',
				icon: 'https://www.fis.ink/img/logo_c.png',
				avatar: 'https://www.fis.ink/img/logo.png',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2026-07-01',
				comment: '博客/服务器技术实践、生活记录、资源分享。',
			},
			{
				author: '栖童',
				title: '栖童の小站',
				desc: '越努力,越幸运',
				link: 'https://blog.linux-qitong.top/',
				feed: 'https://blog.linux-qitong.top/atom.xml',
				icon: 'https://blog.linux-qitong.top/img/favicon.webp',
				avatar: 'https://blog.linux-qitong.top/img/avatar.webp',
				archs: ['Nuxt', 'Vercel'],
				date: '2026-07-01',
				comment: '原名青稚，博客记录Linux使用、博客部署、生活反思。',
			},
			{
				author: '灯火不休时',
				desc: '所爱隔山海，山海不可平；所念皆星河，星河不可及',
				link: 'https://blog.dhbxs.top/',
				feed: 'https://blog.dhbxs.top/feed.xml',
				icon: 'https://file.dhbxs.top/2026/01/nllahmfi.png',
				avatar: 'https://file.dhbxs.top/ylvwvjjs.jpg',
				archs: ['Halo', '国内 CDN'],
				date: '2026-07-01',
				comment: '深度学习、大数据与软件工程学习笔记。',
			},
			{
				author: '敖苛记',
				desc: '敖致天，苛制人',
				link: 'https://blog.kayro.cn/',
				feed: 'https://blog.kayro.cn/atom.xml',
				icon: 'https://blog.kayro.cn/favicon.svg',
				avatar: 'https://blog.kayro.cn/avatar.webp',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2026-07-01',
				comment: '分享系统搭建、工具配置、AI 部署及编程学习笔记的技术博客。',
			},
		],
	},
	// #endregion
	// #region 网上邻居 since 2026-07-02
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: 'isYangs',
				desc: '一个前端Bug构造师的博客',
				link: 'https://www.isyangs.cn/',
				feed: 'https://www.isyangs.cn/feed.xml',
				icon: 'https://www.isyangs.cn/favicon.svg',
				avatar: 'https://www.isyangs.cn/favicon.svg',
				archs: ['Vue', '国内 CDN'],
				date: '2026-07-02',
				comment: '目前从事前端开发。',
			},
			{
				author: '桜紺狸',
				sitenick: '部落阁',
				title: '桜紺狸の部落阁',
				desc: '一个闲聊萌新动漫技术交流站',
				link: 'https://www.skira.top/',
				feed: 'https://www.skira.top/feed.xml',
				icon: 'https://www.skira.top/img/skira.ico',
				avatar: 'https://www.skira.top/img/lemonsuka.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2026-07-02',
				comment: '搞机发烧友，小众系统爱好者，前端研究员。',
			},
			{
				author: '张洪Heo',
				desc: '分享设计与科技生活',
				link: 'https://blog.zhheo.com/',
				feed: 'https://blog.zhheo.com/atom.xml',
				icon: 'https://blog.zhheo.com/img/favicon4.0.webp',
				avatar: 'https://blog.zhheo.com/img/favicon4.0.webp',
				archs: ['Hexo', '国内 CDN'],
				date: '2026-07-02',
				comment: '知名博主，其博客设计风格被众多人借鉴。',
			},
			{
				author: 'Revincx',
				sitenick: '小破站',
				title: 'Revincx的小破站',
				link: 'https://blog.revincx.icu/',
				feed: 'https://blog.revincx.icu/atom.xml',
				icon: 'https://blog.revincx.icu/images/favico.png',
				avatar: 'https://weavatar.com/avatar/20eed6a268787c9a751165bc1ec56e90',
				archs: ['Hexo', 'Vercel'],
				date: '2026-07-02',
				comment: '折腾。',
			},
			{
				author: 'Yunyi',
				title: 'YUNYI BLOG',
				desc: '得闲饮茶~~~',
				link: 'https://www.yunyitang.me/',
				feed: 'https://www.yunyitang.me/atom.xml',
				icon: 'https://www.yunyitang.me/favicon/favicon.ico',
				avatar: 'https://www.yunyitang.me/img/Avatar.png',
				archs: ['Hexo', 'GitHub Pages'],
				date: '2026-07-02',
				comment: '很有博客的味道。',
			},
			{
				author: '晓空',
				sitenick: '空域',
				title: '晓空blog',
				desc: '探索更大的世界',
				link: 'https://blog.moeworld.tech/',
				feed: 'https://blog.moeworld.tech/feed/',
				icon: 'https://blog.moeworld.tech/wp-content/uploads/2024/08/cropped-favicon-32x32.png',
				avatar: 'https://blog.moeworld.tech/wp-content/themes/kratos-pjax-master/static/images/photo.jpg',
				archs: ['WordPress', 'Cloudflare'],
				date: '2026-07-02',
				comment: '技术折腾笔记。',
			},
			{
				author: 'Kegongteng',
				desc: 'Blogger / Technophile / Student',
				link: 'https://kegongteng.cn/',
				feed: 'https://kegongteng.cn/atom',
				icon: 'https://kegongteng.cn/favicon.ico',
				avatar: 'https://weavatar.com/avatar/0b01396273cca253aa6876c020449b655a9cc12e75f921b38ac088569e814b5e',
				archs: ['Next.js', 'Netlify'],
				date: '2026-07-02',
				comment: '有不错想法的开发者。',
			},
			{
				author: '洛寒兮',
				title: 'I\'m Luochancy',
				desc: '这是个猫猫的博客喵～',
				link: 'https://www.luochancy.com/',
				feed: 'https://www.luochancy.com/feed',
				icon: 'https://www.luochancy.com/wp-content/uploads/2023/10/cropped-231026_head_image-32x32.png',
				avatar: 'https://www.luochancy.com/wp-content/uploads/2023/12/1904634_Ehaif6np.png',
				archs: ['WordPress', '国内 CDN'],
				date: '2026-07-02',
				comment: '学生',
			},
			{
				author: '斬風·千雪',
				sitenick: '風雪城',
				desc: '浩繁星空下的一场稚嫩的梦',
				link: 'https://blog.chyk.ink/',
				feed: 'https://blog.chyk.ink/atom.xml',
				icon: getGithubIcon('chiyuki0325'),
				avatar: getOicqAvatar('3526514925'),
				archs: ['Hexo', 'Vercel'],
				date: '2026-07-02',
				comment: 'Archlinux，折腾。',
			},
			{
				author: '清羽飞扬',
				title: 'LiuShen\'s Blog',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: 'https://blog.liushen.fun/info/avatar.ico',
				avatar: 'https://weavatar.com/avatar/92c15d4a1d99a8ee04b986a14a5f7e009e574b3383fc575005947988ccf205e2',
				archs: ['Hexo', '国内 CDN'],
				date: '2026-07-02',
				comment: '武理工学长。',
			},
			{
				author: 'awaae',
				sitenick: '呓语梦轩',
				desc: '用心享受生活',
				link: 'https://blog.awaae001.top/',
				feed: 'https://blog.awaae001.top/atom.xml',
				icon: getFavicon('blog.awaae001.top'),
				avatar: getGithubAvatar('awaae001'),
				archs: ['Next.js', 'Vercel'],
				date: '2026-07-02',
				comment: '有思考的学生。',
			},
			{
				author: 'FloatSheep',
				title: 'FloatSheep\'s Blog',
				desc: 'On the other side of obstacles',
				link: 'https://blog.hesiy.cn/',
				feed: 'https://blog.hesiy.cn/posts/index.xml',
				icon: 'https://blog.hesiy.cn/favicon-32x32.png',
				avatar: getGithubAvatar('FloatSheep'),
				archs: ['Hugo', 'Cloudflare'],
				date: '2026-07-02',
				comment: '喜欢折腾。',
			},
			{
				author: 'Henry',
				sitenick: '一站',
				title: '一站 - Henry的博客',
				desc: 'Student / Designer / Dreamchaser',
				link: 'https://henry.city/blog/',
				feed: 'https://henry.city/blog/atom.xml',
				icon: 'https://henry.city/blog/favicon.ico',
				avatar: 'https://henry.city/blog/images/avatar.png',
				archs: ['Gridea', '服务器'],
				date: '2026-07-03',
				comment: '很有博客的味道。',
			},
			{
				author: 'iMaeGoo',
				sitenick: '空间站',
				title: '虹墨空间站',
				desc: '虹墨空间站',
				link: 'https://www.imaegoo.com/',
				feed: 'https://www.imaegoo.com/atom.xml',
				icon: 'https://www.imaegoo.com/favicon.ico',
				avatar: 'https://www.imaegoo.com/images/avatar.jpg',
				archs: ['Hexo', '国内 CDN'],
				date: '2026-07-03',
				comment: '前端折腾。',
			},
			{
				author: 'DuckXu',
				title: '悦绮录',
				desc: '悦己绮世，自由如风。',
				link: 'https://i.duckxu.com',
				feed: 'https://i.duckxu.com/rss.xml',
				icon: 'https://media.duckxu.com/blogfiles/public/iduckxucom.webp',
				avatar: getGithubAvatar('ScDuckXu'),
				archs: ['Typecho', '服务器'],
				date: '2026-07-03',
				comment: '记录生活思考。',
			},
			{
				author: 'DengQN',
				title: 'DengQN\'s Blog',
				desc: '普通程序员',
				link: 'https://dengqn.com/',
				feed: 'https://dengqn.com/feed',
				icon: 'https://dengqn.com/favicon.ico',
				avatar: 'https://dengqn.com/headimg.png',
				archs: ['Vue', 'Cloudflare'],
				date: '2026-07-03',
				comment: '技术吐槽和运维记录。',
			},
			{
				author: 'LineXic',
				desc: '念念不忘，必有回响',
				link: 'https://www.linexic.top/',
				feed: 'https://www.linexic.top/rss.xml',
				icon: 'https://www.linexic.top/logo.png',
				avatar: 'https://www.linexic.top/avatar.webp',
				archs: ['Astro', 'Netlify'],
				date: '2026-07-03',
				comment: '前端学习，生活。',
			},
			{
				author: 'tinsir888',
				desc: 'Ηλύσια Πεδία',
				title: 'min hjemmeside',
				link: 'https://tinsir888.github.io/',
				feed: 'https://tinsir888.github.io/atom.xml',
				icon: getGithubIcon('tinsir888'),
				avatar: getGithubAvatar('tinsir888'),
				archs: ['Hexo', 'GitHub Pages'],
				date: '2026-07-03',
				comment: '计算机科学，留学生活。',
			},
			{
				author: 'XAOXUU',
				desc: '风暴前夕',
				link: 'https://xaoxuu.com/',
				feed: 'https://xaoxuu.com/atom.xml',
				icon: getGithubIcon('xaoxuu'),
				avatar: getGithubAvatar('xaoxuu'),
				archs: ['Hexo', '服务器'],
				date: '2026-07-03',
				comment: '产品与博客思考，本博客网站设计的重要参考。',
			},
			{
				author: 'Pinpe',
				sitenick: '云端',
				title: 'Pinpe的云端',
				desc: '一个属于自己的云朵。',
				link: 'https://pinpe.top/',
				feed: 'https://pinpe.top/rss.xml',
				icon: 'https://pinpe.top/favicon/logo.jpg',
				avatar: 'https://pinpe.top/head.jpg',
				archs: ['Astro', 'Vercel'],
				date: '2026-07-04',
				comment: '奇妙幻想和思考。',
			},
			{
				author: '水氵冫',
				sitenick: '微霞',
				desc: '水风清，晚霞明',
				link: 'https://yuuu.org/',
				feed: 'https://yuuu.org/atom.xml',
				icon: 'https://cdn.yuuu.org/img/favicon-32x32.png',
				avatar: 'https://cdn.yuuu.org/img/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2026-07-04',
				comment: '技术分享，生活。',
			},
			{
				author: 'Tianli',
				desc: '自知之明是最可贵的知识！',
				link: 'https://blog.tianli0.top/',
				feed: 'https://blog.tianli0.top/rss.xml',
				icon: getGithubIcon('tianli0'),
				avatar: getGithubAvatar('tianli0'),
				archs: ['VitePress', '国内 CDN'],
				date: '2026-07-04',
				comment: '技术学习笔记，TianliGPT开发者。',
			},
			// #region 2026-07-05
			{
				author: '鸢栀',
				sitenick: '仓库',
				title: '鸢栀的仓库',
				desc: '每天写下自己的喜欢',
				link: 'https://yuazhi.cn/',
				icon: 'https://yuazhi.cn/yuazhi.ico',
				avatar: 'https://weavatar.com/avatar/1dc444f85a6673099a47170588bbc6d7?s=96',
				archs: ['HTML', '服务器'],
				date: '2026-07-05',
				comment: '日常、前端、福瑞。',
			},
			{
				author: '葱苓',
				sitenick: '语畔',
				title: '葱苓语畔',
				desc: 'Don\'t worry, be happy.',
				link: 'https://blog.ciraos.top/',
				feed: 'https://blog.ciraos.top/feed.xml',
				icon: 'https://blog.ciraos.top/favicon.ico',
				avatar: getGithubAvatar('ciraos'),
				archs: ['Hexo', '国内 CDN'],
				date: '2026-07-05',
				comment: '前端学习。',
			},
			{
				author: 'ZL Asica',
				title: 'ZLA 小站',
				desc: '月亮不抱你，星星会落在你怀里✨🌙',
				link: 'https://zla.pub/',
				feed: 'https://zla.pub/feed.xml',
				icon: getGithubIcon('ZL-Asica'),
				avatar: getGithubAvatar('ZL-Asica'),
				archs: ['Next.js', 'Vercel'],
				date: '2026-07-05',
				comment: '机器学习、前端开发、旅游经历。',
			},
			{
				author: '竹林里有冰',
				title: '竹林里有冰的博客',
				desc: '仍然在划水的菜鸡',
				link: 'https://zhul.in/',
				feed: 'https://zhul.in/rss.xml',
				icon: 'https://zhul.in/favicon.ico',
				avatar: 'https://static.031130.xyz/avatar.webp',
				archs: ['Nuxt', '服务器'],
				date: '2026-07-05',
				comment: '前端开发、网络配置、服务器运维及开源工具实战经验。',
			},
			{
				author: 'Teror Fox',
				sitenick: '客栈',
				title: 'Teror的客栈',
				desc: '欢迎光临～',
				link: 'https://blog.trfox.top/',
				feed: 'https://blog.trfox.top/atom.xml',
				icon: 'https://blog.trfox.top/favicon.ico',
				avatar: 'https://img.trfox.top/assets/avatar.jpg',
				archs: ['Next.js', 'Vercel'],
				date: '2026-07-05',
				comment: '技术相关的木马免杀测试、服务器处理与迁移、工具美化，以及个人博客系统更新、回归记录等。',
			},
			{
				author: 'Snowykami',
				sitenick: '空间站',
				title: 'Snowykami\'s Blog',
				desc: '轻思若水，雪化生香',
				link: 'https://blog.sfkm.me/',
				feed: 'https://blog.sfkm.me/feed.xml',
				icon: getOicqAvatar('2751454815', OicqAvatarSize.Size100),
				avatar: getOicqAvatar('2751454815'),
				archs: ['Hexo', '国内 CDN'],
				date: '2026-07-05',
				comment: '云原生、HomeLab 搭建、网络安全、容器化、静态网站托管等领域的技术实践。',
			},
			{
				author: '酥米',
				title: '酥米的小站',
				desc: '终有一日，寻梦中人',
				link: 'https://www.sumi233.top/',
				feed: 'https://www.sumi233.top/atom.xml',
				icon: 'https://www.sumi233.top/favicon.ico',
				avatar: 'https://cdn.sumi233.top/gh/huang233893/blog-image-bed/top/huang233893/imgs/blog/userfb6a1018b84ce485.jpg',
				archs: ['Hexo', '国内 CDN'],
				date: '2026-07-05',
				comment: '计算机网络知识，设备折腾。',
			},
			{
				author: 'kzhik',
				title: 'kzhik\'s website',
				desc: '前端/网络技术实践与个人记录',
				link: 'https://www.kzhik.cn/',
				feed: 'https://www.kzhik.cn/resources/rss.xml',
				icon: 'https://www.kzhik.cn/favicon.ico',
				avatar: 'https://www.kzhik.cn/avatar.webp',
				archs: ['Nuxt', '国内 CDN'],
				date: '2026-07-05',
				comment: '前端/网络技术实践与个人记录',
			},
			{
				author: 'Saneko',
				sitenick: '星屿浅奈',
				title: '星屿浅奈 ✧ Saneko',
				desc: 'Do the things that I like.',
				link: 'https://saneko.me/',
				feed: 'https://saneko.me/atom.xml',
				icon: 'https://cdn.blog.saneko.me/Web/Avatar.png',
				avatar: 'https://cdn.blog.saneko.me/Web/Avatar.png',
				archs: ['Astro', '服务器'],
				date: '2026-07-05',
				comment: '曾叫ATao，技术实践与问题解决方案',
			},
			{
				author: 'Elykia',
				title: '致以无暇之人',
				desc: '爱莉希雅永远爱你～',
				link: 'https://blog.elykia.cn/',
				feed: 'https://blog.elykia.cn/atom.xml',
				icon: 'https://doge.elykia.cn/favicon.ico',
				avatar: getGithubAvatar('Elykia093'),
				archs: ['Hexo', '国内 CDN'],
				date: '2026-07-05',
				comment: 'Hexo 安知鱼主题美化。',
			},
			{
				author: 'VnYzm',
				title: 'VnYzm的博客',
				desc: '分享技术心得和摸鱼感想',
				link: 'https://vnyzm.top/',
				feed: 'https://vnyzm.top/extra/atom.xml',
				icon: 'https://vnyzm.top/img/favicon.ico',
				avatar: 'https://vnyzm.top/img/profile.jpg',
				archs: ['Python', 'GitHub Pages'],
				date: '2026-07-05',
				comment: '动漫观后感、游戏玩后感、技术笔记。',
			},
			{
				author: '七十二时.',
				desc: '咸鱼发呆时刻。一条咸鱼的发呆据点，也是我的实验日志。',
				link: 'https://www.qsesvick.top/',
				feed: 'https://www.qsesvick.top/feed/',
				icon: getFavicon('qsesvick.top'),
				avatar: 'https://files3.qsesvick.top/JCZY/LOGO/YJQSES.png',
				archs: ['WordPress', 'Cloudflare'],
				date: '2026-07-05',
				comment: '工具分享，博客折腾。',
			},
			{
				author: 'Sakun',
				sitenick: 'Notebook',
				title: 'Sakun Notebook',
				desc: 'Sakun Notebook',
				link: 'https://www.sakun.space/',
				feed: 'https://www.sakun.space/atom.xml',
				icon: 'https://www.sakun.space/images/favicon-32x32-next.png',
				avatar: 'https://www.sakun.space/images/avatar.png',
				archs: ['Hexo', '服务器'],
				date: '2026-07-05',
				comment: '动漫评论。',
			},
			{
				author: '伏枥',
				sitenick: '伏枥之间',
				desc: '莫听穿林打叶声，何妨吟啸且徐行。',
				link: 'https://www.leehenry.top/',
				feed: 'https://www.leehenry.top/rss.xml',
				icon: 'https://www.leehenry.top/favicon.ico',
				avatar: 'https://leehenry.top/friends/my-avatar-portrait.jpg',
				archs: ['Astro', '服务器'],
				date: '2026-07-05',
				comment: '生活分享、社会思考与技术探索。',
			},
			{
				author: '广树',
				sitenick: '维基萌',
				desc: '萌即是正义！时不时分享一些ACG活动记录与有趣代码的小站！',
				link: 'https://panda.wikimoe.com/',
				feed: 'https://panda.wikimoe.com/rss/blog',
				icon: 'https://panda.wikimoe.com/upload/siteImg/siteFavicon.png',
				avatar: 'https://panda.wikimoe.com/upload/avatar/65994c0f3af05a21862459e9.webp',
				archs: ['Nuxt', 'Cloudflare'],
				date: '2026-07-05',
				comment: '游戏数据/圣地巡礼/代码笔记。',
			},
			{
				author: '异想之旅',
				desc: '异想之旅のBlog',
				link: 'https://yxzl.dev/',
				icon: 'https://yxzl.dev/favicon.ico',
				avatar: 'https://yxzl.dev/favicon.ico',
				archs: ['VuePress', 'Cloudflare'],
				date: '2026-07-05',
				comment: 'Python、Vue与算法。',
			},
			{
				author: 'iamyukino',
				sitenick: '雨雪冰屋',
				desc: '一隅雨雪一炉窝，可能会融化持久堆？',
				link: 'https://iamyukino.cn/blog/',
				feed: 'https://iamyukino.cn/atom.xml',
				icon: 'https://iamyukino.cn/favicon.ico',
				avatar: 'https://iamyukino.cn/blog/assets/home/home.jpg',
				archs: ['Astro', '服务器'],
				date: '2026-07-05',
				comment: '主页十分可爱的个人小站，记录编程技术学习经历。',
			},
			{
				author: '手里有只毛毛虫',
				desc: '号角声起 - 等你启航',
				link: 'https://www.krjojo.com/',
				feed: 'https://www.krjojo.com/feed',
				icon: 'https://www.krjojo.com/favicon.ico',
				avatar: 'https://www.krjojo.com/favicon.ico',
				archs: ['WordPress', 'Cloudflare'],
				date: '2026-07-05',
				comment: '前端运维和生活思考。',
			},
			{
				author: 'cosine',
				sitenick: '余弦',
				title: '余弦の博客',
				desc: '= WA 的一声就哭了 =',
				link: 'https://blog.cosine.ren/',
				feed: 'https://blog.cosine.ren/rss.xml',
				icon: 'https://blog.cosine.ren/favicon.ico',
				avatar: 'https://blog.cosine.ren/img/avatar.webp',
				archs: ['Astro', 'Vercel'],
				date: '2026-07-05',
				comment: '“FE / ACG / 手工 / 深色模式强迫症 / INFP / 兴趣广泛养两只猫的老宅女 / remote”，运营《前端周周谈 FE Bits》周刊。',
			},
			{
				author: '棋',
				sitenick: 'ImQi1',
				desc: '做技术的分享者、生活的摄影师、时事的评论员。',
				link: 'https://imqi1.com/',
				feed: 'https://imqi1.com/feed/',
				icon: 'https://imqi1.com/favicon.ico',
				avatar: getGithubAvatar('imqi1-github'),
				archs: ['Nuxt', 'EdgeOne'],
				date: '2026-07-05',
				comment: '博客技术与生活分享。',
			},
			// #region 2026-07-06
			{
				author: '见崎美咲',
				sitenick: 'Catarium',
				desc: '见崎的猫箱',
				link: 'https://catarium.me/',
				feed: 'https://catarium.me/atom.xml',
				icon: 'https://catarium.me/favicon.svg',
				avatar: getGithubAvatar('Eofs791'),
				archs: ['Astro', 'Cloudflare'],
				date: '2026-07-06',
				comment: '加拿大留子，二次元。',
			},
			{
				author: '23朵毒蘑菇',
				desc: '一个简单的前端开发者。',
				link: 'https://blog.dumogu.top/',
				feed: 'https://blog.dumogu.top/rss.xml',
				icon: 'https://blog.dumogu.top/web-assets/v-last/public/favicon.ico',
				avatar: 'https://blog.dumogu.top/web-assets/v-last/public/user.jpg',
				archs: ['Express', '服务器'],
				date: '2026-07-06',
				comment: '捣鼓了不少东西的前端程序员。',
			},
			{
				author: 'Viki',
				title: 'Viki 写东西的地方',
				desc: '生活需要记录。',
				link: 'https://blog.viki.moe/',
				feed: 'https://blog.viki.moe/rss',
				icon: 'https://blog.viki.moe/favicon.ico',
				avatar: 'https://blog.viki.moe/avatar.png',
				archs: ['Next.js', 'Vercel'],
				date: '2026-07-06',
				comment: '前端大手子，博客与前端知识分享。',
			},
			{
				author: 'Mr.Lee',
				sitenick: '里世界',
				desc: 'Welcome to the world of Lee',
				link: 'https://leenet.xyz/',
				feed: 'https://leenet.xyz/atom.xml',
				icon: 'https://leenet.xyz/favicon.svg',
				avatar: 'https://leenet.xyz/avatar.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2026-07-06',
				comment: 'TUI风格的Nuxt博客，讲述博客技术学习历程。',
			},
			{
				author: 'bakaptr',
				title: 'Nostalgia Garden',
				desc: 'I\'m a person dedicated to what I am interested in.',
				link: 'https://rua.sh/',
				feed: 'https://rua.sh/rss.xml',
				icon: getGithubIcon('Zhousiru'),
				avatar: getGithubAvatar('Zhousiru'),
				archs: ['Astro', 'Cloudflare'],
				date: '2026-07-06',
				comment: '前端大手子。',
			},
			{
				author: 'LuckyFish',
				title: 'NoName Blog',
				desc: '一条鱼的自娱自乐',
				link: 'https://blog.luckyfishes.site/',
				feed: 'https://blog.luckyfishes.site/rss.xml',
				icon: 'https://blog.luckyfishes.site/favicon.ico',
				avatar: getOicqAvatar('2383690354'),
				archs: ['Next.js', 'Vercel'],
				date: '2026-07-06',
				comment: '“老八校”西建大iOS Club前社长，但任职期间没有苹果设备。',
			},
			{
				author: 'Almango',
				sitenick: '啊芒果',
				desc: '天真永不消逝，浪漫至死不渝',
				link: 'https://blog.almango.cn/',
				feed: 'https://blog.almango.cn/rss.xml',
				icon: 'https://blog.almango.cn/favicon.png',
				avatar: 'https://blog.almango.cn/favicon.png',
				archs: ['Astro', 'Vercel'],
				date: '2026-07-06',
				comment: '编程入门、博客搭建、游戏生活为主的个人成长向技术博客，系统记录C#/C++/Python/前端等学习笔记、Hexo/Astro建站与主题开发、MC服务器开服日志，同时包含年度总结与游戏感悟。',
			},
			{
				author: '张小阳',
				sitenick: 'CodeVoy',
				desc: '知识管理与技术分析',
				link: 'https://www.zzyang.top/',
				feed: 'https://www.zzyang.top/rss.xml',
				icon: 'https://www.zzyang.top/favicon/avatar.png',
				avatar: 'https://www.zzyang.top/favicon/avatar.png',
				archs: ['Astro', '服务器'],
				date: '2026-07-06',
				comment: '分享Java后端、数据库与AI实战的技术博客',
			},
			{
				author: 'HongLiu',
				sitenick: '小站',
				title: 'HongLiu的小站',
				desc: '做自己所爱的事，爱自己所做的事。',
				link: 'https://hongliu.icu',
				feed: 'https://hongliu.icu/rss.xml',
				icon: 'https://hongliu.icu/image/avator_1.jpg',
				avatar: 'https://hongliu.icu/image/avator_1.jpg',
				archs: ['Hexo', 'GitHub Pages'],
				date: '2026-07-06',
				comment: '工科生技术与生活博客，记录机器人、电子、编程学习、开源项目与日常随笔。',
			},
			{
				author: '焰白',
				sitenick: 'Enento',
				title: 'Enento焰白小站',
				desc: '百次思考，千次落笔，刻下万次记忆',
				link: 'https://enento.cloud/',
				feed: 'https://www.enento.cloud/rss.xml',
				icon: 'https://enento.cloud/upload/1da41c9c-a767-4b17-8cfd-909e9930109f.png',
				avatar: 'https://www.enento.cloud/upload/Enentoico.jpg',
				archs: ['Halo', '服务器'],
				date: '2026-07-06',
				comment: '艺术人文编程自设。',
			},
			{
				author: 'LHL',
				title: 'LHL’s Blog',
				desc: '能烂尾的结局，过程一定很精彩',
				link: 'https://blog.lhl.one/',
				feed: 'https://blog.lhl.one/rss.xml',
				icon: 'https://blog.lhl.one/favicon.ico',
				avatar: 'https://smms-vip3.see.you/2025/04/18/KXpf8u5SQYNPkA3.jpg',
				archs: ['Typecho', '服务器'],
				date: '2026-07-06',
				comment: '聚焦 Typecho 主题与插件开发、各类工具二次开发及运维排障的技术博客。',
			},
			{
				author: 'fiee',
				title: 'Fiee\'s Blog',
				desc: '“长风破浪会有时，直挂云帆济沧海”',
				link: 'https://www.aifiee.cn',
				avatar: 'https://aifiee-blog.oss-cn-beijing.aliyuncs.com/blog/images/1782719333889_1414.jpg',
				icon: 'https://aifiee-blog.oss-cn-beijing.aliyuncs.com/blog/images/1782719333889_1414.jpg',
				archs: ['Vue', 'React'],
				date: '2026-07-09',
				comment: '有关前端笔记、后端技术的一个年轻博客。',
			},
			{
				author: 'AndyJin',
				title: 'Modern Blog',
				desc: '分享技术，记录生活',
				link: 'https://blog.andyjin.website',
				feed: 'https://blog.andyjin.website/atom.xml',
				avatar: 'https://filestorage0.oss-cn-hongkong.aliyuncs.com/avatar.png',
				icon: 'https://blog.andyjin.website/img/fluid.png',
				archs: ['Hexo', 'Python'],
				date: '2026-07-11',
				comment: '记录技术思考与生活感悟，分享有趣的知识与经验',
			},
			{
				author: 'LazyCatttt',
				title: '浮生',
				desc: '无人扶我青云志，我自踏雪至山巅',
				link: 'https://maozm.art/',
				avatar: 'https://maozm.art/assets/profile-avatar.webp',
				icon: 'https://maozm.art/assets/favicon-96.png',
				archs: ['C语言', 'Python'],
				date: '2026-07-11',
				comment: '文绉绉的程序员，可爱的博客',
			},
			{
				author: 'Odonata',
				title: '蜓留',
				desc: '飞行于世，栖息于此',
				link: 'https://odonata.top/',
				feed: 'https://odonata.top/rss.xml',
				avatar: 'https://odonata.top/img/holo.jpg',
				icon: 'https://odonata.top/favicon.ico',
				archs: ['Astro', 'Rust'],
				date: '2026-08-10',
				comment: '学习心得、思考感悟、折腾记录、日常随笔、零散想法，以及那些不想被遗忘的小事',
			},
			{
				author: '23朵毒蘑菇',
				title: '23朵毒蘑菇',
				desc: '面对死亡时，我们只说一句话， 时辰未到！',
				link: 'https://blog.dumogu.top/',
				avatar: 'https://blog.dumogu.top/logo',
				icon: 'https://blog.dumogu.top/favicon.ico',
				archs: ['Vue', 'Express'],
				date: '2026-08-17',
				comment: '简单的博客设计风格，但内涵很丰富',
			},
			/* ========从此处新增友链======== */
		],
	},
	// #endregion

	// #region 知识分享
	{
		name: '知识分享',
		desc: '创作分享/知识内容收集。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '静かな森',
				desc: '致虚极，守静笃。',
				link: 'https://innei.in/',
				feed: 'https://innei.in/feed',
				icon: 'https://innei.in/innei.svg',
				avatar: getGithubAvatar('Innei'),
				archs: ['Next.js', 'Cloudflare'],
				date: '2026-07-06',
			},
			{
				author: '茂茂物语',
				desc: '茂茂的成长之路，包含前端常用知识、源码阅读笔记、各种奇淫技巧、日常提效工具等',
				link: 'https://notes.fe-mm.com/',
				icon: getGithubIcon('maomao1996'),
				avatar: getGithubAvatar('maomao1996'),
				archs: ['VitePress', 'Cloudflare'],
				date: '2026-07-06',
				comment: '前端开发笔记。',
			},
			{
				author: '石头',
				sitenick: '铭心石刻',
				title: '铭心石刻',
				desc: '愿岁并谢，与友长兮',
				link: 'https://blog.kouseki.cn/',
				feed: 'https://blog.kouseki.cn/rss.xml',
				icon: 'https://blog.kouseki.cn/favicon.ico',
				avatar: 'https://blog.kouseki.cn/imgs/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2026-07-06',
				comment: '折腾Hexo博客，友链页面蛮多博客折腾选手的。',
			},
			{
				author: '浪海导航',
				desc: '收录各种类型的博客以及论坛网站',
				link: 'https://www.langhai.net/',
				icon: 'https://www.langhai.net/assets/images/langhai-logo.png',
				avatar: 'https://www.langhai.net/assets/images/langhai-logo.png',
				archs: ['Hugo', 'Cloudflare'],
				date: '2026-07-06',
			},
			{
				author: '十玖八柒',
				sitenick: 'Z次元',
				desc: '探索代码的世界，追寻生活的诗篇',
				link: 'https://blog.ahzoo.cn/',
				feed: 'https://blog.ahzoo.cn/rss.xml',
				icon: 'https://blog.ahzoo.cn/favicon.ico',
				avatar: 'https://ahzoo.cn/img/avatar.webp',
				archs: ['Nuxt', '服务器'],
				date: '2026-07-06',
				comment: 'Nuxt博客，技术笔记。',
			},
			{
				author: '菜园前端',
				desc: '前端学习笔记分享、小白都能看懂的笔记',
				link: 'https://note.noxussj.top/?s=y9',
				icon: 'https://note.noxussj.top/logo.png',
				avatar: getGithubAvatar('noxussj2'),
				archs: ['VitePress', '服务器'],
				date: '2026-07-06',
				comment: '前端学习笔记。',
			},
			{
				author: '無名',
				sitenick: '小栈',
				title: '無名小栈',
				desc: '分享技术与科技生活',
				link: 'https://blog.imsyy.top/',
				feed: 'https://blog.imsyy.top/rss.xml',
				icon: getFavicon('blog.imsyy.top'),
				avatar: getGithubAvatar('imsyy'),
				archs: ['VitePress', 'Vercel'],
				date: '2026-07-06',
			},
			{
				author: 'AiQiji·工具箱',
				desc: '为开发者、设计师和效率工具爱好者精心收集的工具导航站点。让工作更高效，让创作更便捷。',
				link: 'https://tools.aiqji.com/',
				icon: 'https://tools.aiqji.com/favicon.ico',
				avatar: 'https://tools.aiqji.com/favicon.ico',
				archs: ['React', 'Cloudflare'],
				date: '2026-07-06',
			},
			{
				author: '阿呆',
				title: '阿呆的博客',
				desc: '分享，学习有趣的知识',
				link: 'https://adaiblog.github.io/',
				feed: 'https://adaiblog.github.io/atom.xml',
				icon: 'https://adaiblog.github.io/favicon.ico',
				avatar: 'https://adaiblog.github.io/img/adai.png',
				archs: ['Hexo', 'GitHub Pages'],
				date: '2026-07-06',
				comment: '技术分享与生活。',
			},
			{
				author: '硅基漫游指南',
				desc: '等待和犹豫才是这个世界上最无情的杀手',
				link: 'https://blog.helong.online/',
				feed: 'https://blog.helong.online/atom.xml',
				icon: 'https://blog.helong.online/icon.png',
				avatar: 'https://oss.helong.online/bucket-IMG/avatar.png',
				archs: ['Nuxt', '国内 CDN'],
				date: '2026-07-06',
				comment: '运维笔记与经验分享。',
			},
			{
				author: '墨韵先知',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://www.htmacg.cn/',
				feed: 'https://www.htmacg.cn/feed',
				icon: 'https://www.htmacg.cn/wp-content/uploads/2026/07/ava_compressed.png',
				avatar: 'https://www.htmacg.cn/wp-content/uploads/2026/07/ava_compressed.png',
				archs: ['WordPress', '国内 CDN'],
				date: '2026-07-06',
				comment: '原名胡桃木实验室，具有运维/系统等技术分享。',
			},
			{
				author: 'bbb-lsy07',
				desc: '科技激荡人文，洞见智慧本真。',
				link: 'https://blog.tsoo.net/',
				feed: 'https://blog.tsoo.net/rss.xml',
				icon: 'https://blog.tsoo.net/upload/lsyb.png',
				avatar: 'https://blog.tsoo.net/upload/logo.jpg',
				archs: ['Halo', '服务器'],
				date: '2026-07-06',
				comment: '建站与笔记。',
			},
			{
				author: '故河',
				title: 'Guhe Blog',
				desc: '分享技术与生活趣事',
				link: 'https://blog.aevi.top/',
				feed: 'https://blog.aevi.top/feed.xml',
				icon: getFavicon('blog.aevi.top', { provider: 'duckduckgo' }),
				avatar: getGithubAvatar('tongzanyang'),
				archs: ['Halo', '服务器'],
				date: '2026-07-06',
				comment: '自部署服务与博客美化。',
			},
			{
				author: 'Wcowin',
				title: 'Wcowin\'s Blog',
				desc: '循此苦旅，以达星辰',
				link: 'https://wcowin.work/',
				icon: 'https://i.stardots.io/wcowin/1750090373988.png',
				avatar: 'https://s1.imagehub.cc/images/2025/12/06/28380affd86b014a6dcaf082fcc97064.png',
				archs: ['Material for MkDocs', 'GitHub Pages'],
				date: '2026-07-06',
				comment: 'AI/MkDocs个人技术知识库。',
			},
			{
				author: 'Neomelt',
				title: 'Neomelt\'s Blog',
				desc: 'Keep looking, don’t settle',
				link: 'https://www.neomelt.cloud/',
				feed: 'https://www.neomelt.cloud/rss.xml',
				icon: 'https://www.neomelt.cloud/head.jpg',
				avatar: 'https://www.neomelt.cloud/head.jpg',
				archs: ['Astro', 'Vercel'],
				date: '2026-07-06',
				comment: '个人技术学习与实战排障。',
			},
			{
				author: '小慧',
				title: '小慧博客',
				desc: '小慧的技术博客',
				link: 'https://www.itxiaohui.top/',
				feed: 'https://www.itxiaohui.top/rss.xml',
				icon: 'https://blogoss.itxiaohui.top/logo%20-uhlgnmrf.png',
				avatar: 'https://blogoss.itxiaohui.top/2025-10-12-pcrvnluo.png',
				archs: ['Halo', '国内 CDN'],
				date: '2026-07-06',
				comment: '技术学习与博客教程。',
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
